#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOST="${GPU_AGENT_HOST:-0.0.0.0}"
PORT="${GPU_AGENT_PORT:-9000}"
STATE_DIR="${GPU_AGENT_STATE_DIR:-$ROOT_DIR/state}"
LOG_FILE="${GPU_AGENT_SERVER_LOG:-$STATE_DIR/server.log}"
TOKEN_FILE="${GPU_AGENT_TOKEN_FILE:-$STATE_DIR/gpu-agent.token}"
CLIENT_ENV_FILE="${GPU_AGENT_CLIENT_ENV_FILE:-$STATE_DIR/gpu-agent.client.env}"
PUBLIC_HOST="${GPU_AGENT_PUBLIC_HOST:-}"

mkdir -p "$STATE_DIR" "$STATE_DIR/logs" "$STATE_DIR/runs"

if [[ -z "$PUBLIC_HOST" ]]; then
    if command -v hostname >/dev/null 2>&1; then
        PUBLIC_HOST="$(hostname -f 2>/dev/null || hostname)"
    fi
fi

if [[ -z "$PUBLIC_HOST" ]]; then
    echo "Could not determine GPU_AGENT_PUBLIC_HOST automatically" >&2
    exit 1
fi

generate_token() {
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
}

token=""
if [[ -s "$TOKEN_FILE" ]]; then
    token="$(tr -d '\r\n' < "$TOKEN_FILE")"
fi

if [[ -z "$token" ]]; then
    token="$(generate_token)"
    umask 077
    printf '%s\n' "$token" > "$TOKEN_FILE"
fi

chmod 600 "$TOKEN_FILE"

SERVER_URL="http://${PUBLIC_HOST}:${PORT}"

write_client_env_file() {
    umask 077
    {
        printf '# Generated by %s on %s\n' "$0" "$(date -Is)"
        printf '# Source this file on the login node before starting Codex or gpuctl.\n'
        printf '# This is the single handoff file for the GPU bridge.\n'
        printf '#\n'
        printf '# Example:\n'
        printf '#   source %s\n' "$CLIENT_ENV_FILE"
        printf '#   "$GPU_AGENT_CLIENT" health\n'
        printf '#   "$GPU_AGENT_CLIENT" run --cwd /path/to/repo --conda-prefix /path/to/env -- python script.py\n'
        printf '#   "$GPU_AGENT_CLIENT" logs <run_id> --follow\n'
        printf '#\n'
        printf '# Codex instructions:\n'
        printf '#   Use $GPU_AGENT_CLIENT for all GPU-node commands.\n'
        printf '#   Do not SSH to the compute node directly.\n'
        printf '#   Submit work with `gpuctl run`, then poll with `gpuctl status` or `gpuctl logs`.\n'
        printf '#\n'
        printf 'export GPU_AGENT_URL=%q\n' "$SERVER_URL"
        printf 'export GPU_AGENT_TOKEN=%q\n' "$token"
        printf 'export GPU_AGENT_HOSTNAME=%q\n' "$PUBLIC_HOST"
        printf 'export GPU_AGENT_PORT=%q\n' "$PORT"
        printf 'export GPU_AGENT_STATE_DIR=%q\n' "$STATE_DIR"
        printf 'export GPU_AGENT_SERVER_LOG=%q\n' "$LOG_FILE"
        printf 'export GPU_AGENT_TOKEN_FILE=%q\n' "$TOKEN_FILE"
        printf 'export GPU_AGENT_CLIENT_ENV_FILE=%q\n' "$CLIENT_ENV_FILE"
        printf 'export GPU_AGENT_CLIENT=%q\n' "$ROOT_DIR/bin/gpuctl"
        printf 'export GPU_AGENT_SERVER=%q\n' "$ROOT_DIR/bin/gpu-agent-server"
        printf 'export GPU_AGENT_PROJECT_ROOT=%q\n' "$ROOT_DIR"
        printf 'export GPU_AGENT_README=%q\n' "$ROOT_DIR/README.md"
        if [[ -n "${GPU_AGENT_CONDA_SH:-}" ]]; then
            printf 'export GPU_AGENT_CONDA_SH=%q\n' "$GPU_AGENT_CONDA_SH"
        fi
    } > "$CLIENT_ENV_FILE"
    chmod 600 "$CLIENT_ENV_FILE"
}

write_client_env_file

cmd=(
    "$ROOT_DIR/bin/gpu-agent-server"
    --host "$HOST"
    --port "$PORT"
    --state-dir "$STATE_DIR"
)

cmd+=(--token-file "$TOKEN_FILE")

if [[ -n "${GPU_AGENT_CONDA_SH:-}" ]]; then
    cmd+=(--conda-sh "$GPU_AGENT_CONDA_SH")
fi

printf 'GPU bridge server URL: %s\n' "$SERVER_URL"
printf 'GPU bridge token file: %s\n' "$TOKEN_FILE"
printf 'GPU bridge client env: %s\n' "$CLIENT_ENV_FILE"
printf 'GPU bridge server log: %s\n' "$LOG_FILE"

exec "${cmd[@]}" "$@" >>"$LOG_FILE" 2>&1
